if(CLANG_PACKAGES_LTO)
    string(MAKE_C_IDENTIFIER "${RUST_TARGET}" cargo_target)
    string(TOUPPER "${cargo_target}" cargo_target)
    set(cargo_lto_rustflags "CARGO_PROFILE_RELEASE_LTO=thin
                             CARGO_TARGET_${cargo_target}_RUSTFLAGS='-C linker-plugin-lto'")
    set(ffmpeg_lto "--enable-lto=thin")
    if(NOT LLVM_ARCH_HAS_AVX)
        set(zlib_nlto "LTO=0")
    endif()
endif()
